export enum BirdOrder {
  Struthioniformes = 'Struthioniformes',
  Rheiformes = 'Rheiformes',
  Tinamiformes = 'Tinamiformes',
  Casuariiformes = 'Casuariiformes',
  Apterygiformes = 'Apterygiformes',
  Anseriformes = 'Anseriformes',
  Galliformes = 'Galliformes',
  Phoenicopteriformes = 'Phoenicopteriformes',
  Podicipediformes = 'Podicipediformes',
  Columbiformes = 'Columbiformes',
  Mesitornithiformes = 'Mesitornithiformes',
  Pterocliformes = 'Pterocliformes',
  Otidiformes = 'Otidiformes',
  Musophagiformes = 'Musophagiformes',
  Cuculiformes = 'Cuculiformes',
  Caprimulgiformes = 'Caprimulgiformes',
  Opisthocomiformes = 'Opisthocomiformes',
  Gruiformes = 'Gruiformes',
  Charadriiformes = 'Charadriiformes',
  Eurypygiformes = 'Eurypygiformes',
  Phaethontiformes = 'Phaethontiformes',
  Gaviiformes = 'Gaviiformes',
  Sphenisciformes = 'Sphenisciformes',
  Procellariiformes = 'Procellariiformes',
  Ciconiiformes = 'Ciconiiformes',
  Suliformes = 'Suliformes',
  Pelecaniformes = 'Pelecaniformes',
  Cathartiformes = 'Cathartiformes',
  Accipitriformes = 'Accipitriformes',
  Strigiformes = 'Strigiformes',
  Coliiformes = 'Coliiformes',
  Leptosomiformes = 'Leptosomiformes',
  Trogoniformes = 'Trogoniformes',
  Bucerotiformes = 'Bucerotiformes',
  Coraciiformes = 'Coraciiformes',
  Galbuliformes = 'Galbuliformes',
  Piciformes = 'Piciformes',
  Cariamiformes = 'Cariamiformes',
  Falconiformes = 'Falconiformes',
  Psittaciformes = 'Psittaciformes',
  Passeriformes = 'Passeriformes',
}

export const BirdOrderList = Object.values(BirdOrder).sort((a, b) => a.localeCompare(b));
